[env]
TERM = "alacritty"

[window]
padding = { x = 12, y = 12 }
opacity = 0.85
blur = true

[font]
size = 11.0

[font.normal]
family = "Hack"
style = "Regular"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[colors.normal]
black   = "#32344a"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#ad8ee6"
cyan    = "#449dab"
white   = "#787c99"
