github.com:
    users:
        potaterrr:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: potaterrr
