#trackpad

input {
    kb_layout = us
    follow_mouse = 0

    touchpad {
        natural_scroll = true    # Enables natural (reversed) scrolling
        tap-to-click = true      # Allows tapping the trackpad to click
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
}


