# ~/.config/hypr/conf/theme.conf

# --- Global Dark Mode Environment Targets ---

env = QT_QPA_PLATFORMTHEME,qt6ct


decoration {
    rounding = 12
    active_opacity = 1.0
    inactive_opacity = 0.9

    blur {
        enabled = true
        size = 12                     # Increased sample area size (default is usually 3-5)
        passes = 4                    # Increased filtering runs (default is 1-2). Thickens the blur.
        new_optimizations = true
        
        # Stylistic Masking Overrides
        xray = false                  # Keeps windows from blurring windows underneath them
        noise = 0.03                  # Adds a subtle grain texture to mask sharp video pixel artifacts
        contrast = 1.1                # Boosts color depth slightly through the frosted lens
        brightness = 0.95             # Subtle darkening tint to maximize text readability
    }
}

general {
    gaps_in = 5      # Spacing between two open windows
    gaps_out = 10     # Spacing between a window and your screen border
}


