# ~/.config/hypr/conf/autostart.conf

# --- Core System Services ---
exec-once = waybar                                   # Your bottom status bar
exec-once = hyprpaper
exec-once = swaync

# For GTK4 / Libadwaita apps (forces preferred dark color scheme)
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# For GTK3 apps
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
